// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4LnlgeSznMLE-xTB9ah48C76ijJU7JE',
    appId: '1:250485408681:web:081392b845c521044afab8',
    messagingSenderId: '250485408681',
    projectId: 'sacheonseong',
    authDomain: 'sacheonseong.firebaseapp.com',
    storageBucket: 'sacheonseong.firebasestorage.app',
    measurementId: 'G-5Z2HT4M71P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeudVl-zIYCIy0TUZJYohp2HhrYXmbd2M',
    appId: '1:250485408681:android:2a972f24866babbe4afab8',
    messagingSenderId: '250485408681',
    projectId: 'sacheonseong',
    storageBucket: 'sacheonseong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7uk9QCqx98MX2TK5Y-QeNDhGSCO3nSQ',
    appId: '1:250485408681:ios:847625ea84b3b3864afab8',
    messagingSenderId: '250485408681',
    projectId: 'sacheonseong',
    storageBucket: 'sacheonseong.firebasestorage.app',
    iosBundleId: 'com.skydesign.sacheonseong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt7uk9QCqx98MX2TK5Y-QeNDhGSCO3nSQ',
    appId: '1:250485408681:ios:90f8aafbee115dbd4afab8',
    messagingSenderId: '250485408681',
    projectId: 'sacheonseong',
    storageBucket: 'sacheonseong.firebasestorage.app',
    iosBundleId: 'com.example.sacheonseongGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4LnlgeSznMLE-xTB9ah48C76ijJU7JE',
    appId: '1:250485408681:web:a77140f5634108764afab8',
    messagingSenderId: '250485408681',
    projectId: 'sacheonseong',
    authDomain: 'sacheonseong.firebaseapp.com',
    storageBucket: 'sacheonseong.firebasestorage.app',
    measurementId: 'G-S7W335RBEF',
  );
}
